export const Colors =  {
    black: "black",
    white: "white",
    blue: "#009EF5",
    lightBlue: "#a6e0ff",
    green: "green",
    gray:'#5f5f5f',
    Orange :'#ff6347',
    darkOrange:'#cc4f38',
    lightPink:'#fff3f0',
    lightWhite:'#efefef',
    lightGray:'#cecece',
    lightBlue:'#7399bd',
    smokewhite:"#ffffff",
    smokeOrange:"#fff2f0",
    dark:"#222222",
    lgWhite:"#f7f5f5",
}